language: python

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

install: pip install tox-travis

script:
    - tox

after_success:
    - pip install coveralls
    - coveralls

branches:
  only:
    - master

notifications:
    email: false
